name: mt7891-wrt24.10

on:
  workflow_dispatch:
    inputs:
      device:
        description: '选择要编译的机型'
        required: true
        type: choice
        options:
          - abt_asr3000
          - cetron_ct3003
          - cmcc_a10
          - cmcc_rax3000m-emmc-usboffload
          - cmcc_rax3000m-usboffload
          - h3c_nx30pro
          - imou_lc-hx3001
          - jcg_q30
          - konka_komi-a31
          - livinet_zr-3020
          - mt7981-360-t7-108M
          - mt7981-clt-r30b1
          - mt7981-clt-r30b1-112M
          - xiaomi_mi-router-ax3000t
          - xiaomi_mi-router-ax3000t-stock
          - xiaomi_mi-router-wr30u-112m
          - xiaomi_mi-router-wr30u-stock

permissions:
  contents: write

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  BASE_CONFIG_FILE: rax3Km-2410.config
  DIY_P1_SH: scripts/diy-part1.sh
  DIY_P2_SH: scripts/diy-part2.sh
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        device: ${{ github.event.inputs.device }}
      max-parallel: 3
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 初始化环境
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y build-essential git
        sudo timedatectl set-timezone "$TZ"

    - name: 克隆源码
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: 加载自定义配置并设置目标设备
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $BASE_CONFIG_FILE ] && cp $BASE_CONFIG_FILE openwrt/.config
        cd openwrt
        sed -i "/CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_/d" .config
        echo "CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_${{ matrix.device }}=y" >> .config
        echo "CONFIG_TARGET_DEVICE_PACKAGES_mediatek_mt7981_DEVICE_${{ matrix.device }}=\"\"" >> .config
        make defconfig
        chmod +x $DIY_P2_SH
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: 编译固件
      run: |
        cd openwrt
        make -j$(nproc) V=s
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 整理文件
      run: |
        cd openwrt/bin/targets/*/*
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: 上传固件目录
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware_${{ matrix.device }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
