name: "测试 WebDAV 上传 .tar.gz 功能"

on:
  workflow_dispatch:  # 手动触发，用于测试

jobs:
  test-webdav-upload:
    runs-on: ubuntu-22.04  # 使用 GitHub 托管的 Ubuntu 22.04 运行器
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 创建测试文件并压缩
      run: |
        # 创建一个测试目录和文件
        mkdir -p test-dir
        echo "这是一个测试文件，用于验证 WebDAV 上传功能" > test-dir/test-file.txt
        echo "测试文件 2" > test-dir/test-file-2.txt
        ls -l test-dir

        # 压缩为 .tar.gz
        FILE_DATE=$(date +"%Y%m%d%H%M")
        tar -czf "test-archive_$FILE_DATE.tar.gz" -C test-dir .
        ls -l "test-archive_$FILE_DATE.tar.gz"
        echo "已生成压缩文件: test-archive_$FILE_DATE.tar.gz"

    - name: 测试 WebDAV 服务器连通性
      run: |
        echo "测试 WebDAV URL: ${{ secrets.WEBDAV_URL }}"
        curl -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
          -I "${{ secrets.WEBDAV_URL }}/test-upload/" || echo "连通性测试失败"

    - name: 上传 .tar.gz 文件到 WebDAV
      run: |
        FILE_DATE=$(date +"%Y%m%d%H%M")
        echo "尝试上传: test-archive_$FILE_DATE.tar.gz"
        curl -v -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
          -T "test-archive_$FILE_DATE.tar.gz" \
          "${{ secrets.WEBDAV_URL }}/test-upload/test-archive_$FILE_DATE.tar.gz" || {
            echo "上传 test-archive_$FILE_DATE.tar.gz 失败"
            exit 1
          }
        echo "成功上传: test-archive_$FILE_DATE.tar.gz"

    - name: 检查 WebDAV 目录（可选）
      run: |
        curl -v -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
          -X PROPFIND \
          "${{ secrets.WEBDAV_URL }}/test-upload/" \
          -H "Depth: 1" || echo "无法列出目录（可能服务器不支持 PROPFIND）"
