name: "测试 WebDAV 上传功能"

on:
  workflow_dispatch:  # 手动触发，用于测试

jobs:
  test-webdav-upload:
    runs-on: ubuntu-22.04
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 创建测试文件
      run: |
        echo "这是一个测试文件，用于验证 WebDAV 上传功能" > test-file.txt
        echo "测试文件 2" > test-file-2.txt
        ls -l

    - name: 测试 WebDAV 服务器连通性
      run: |
        echo "测试 WebDAV URL: ${{ secrets.WEBDAV_URL }}"
        curl -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
          -I "${{ secrets.WEBDAV_URL }}/test-upload/" || echo "连通性测试失败"

    - name: 上传测试文件到 WebDAV
      run: |
        FILE_DATE=$(date +"%Y%m%d%H%M")
        for file in test-file.txt test-file-2.txt; do
          echo "尝试上传: $file"
          curl -v -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
            -T "$file" \
            "${{ secrets.WEBDAV_URL }}/test-upload/$(basename $file)_$FILE_DATE" || {
              echo "上传 $file 失败"
              exit 1
            }
          echo "成功上传: $(basename $file)"
        done

    - name: 检查 WebDAV 目录（可选）
      run: |
        curl -v -u ${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASSWORD }} \
          -X PROPFIND \
          "${{ secrets.WEBDAV_URL }}/test-upload/" \
          -H "Depth: 1" || echo "无法列出目录（可能服务器不支持 PROPFIND）"
